[package]
name = "test1"
version = "0.0.0"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/move-natives.git", subdir = "initia_stdlib", rev = "main"  }

[addresses]
initia_std = "0x1"
std = "0x1"
cafe = "0xcafe"
TestAccount = "_"
